### PR TITLE
Added support for adding numbered files & XML output

### PR DESCRIPTION
**Pull request by qwertysam**
More info is in the Readme.

You can now specify several numbered files (e.g. `planet0001.png`, `planet0002.png` ... `planet3923.png`) with simple embedded syntax in the input file (e.g. `planet[0001-3923].png`)

This makes animations incredibly easy to add to the texture atlas.

### CODE REVIEW

**Comment by qwertysam** [comment]
XML functionality is operational. 
Also optimised formatting to refrain from including rotation and trim information when it is unnecessary.

**Comment by josefnpat** [comment]
This is a cool feature. I don't know C++, so I hope @urraka reviews this PR.

**Comment by urraka** [comment]
@josefnpat I will! I just haven't had enough time lately.

**Comment by josefnpat** [comment]
@urraka I understand <3

**Comment by urraka** [comment]
I finally reviewed and merged this. Also fixed a couple of things.

@qwertysam Why did you comment out these lines, btw? https://github.com/urraka/texpack/blob/master/src/sebclaeys_xml/XMLWriter.hh#L97

**Comment by qwertysam** [comment]
To be completely honest, I can't remember. As I recall, they had no relevance.

**Pull request merged**
