### PR TITLE
Adds possibility to build on Windows via MSVC using CMake and vcpkg

### PR DESCRIPTION
**Pull request by ghost**
Maybe its useful to you :)

### CODE REVIEW

**Comment by urraka** [comment]
Hi @kerskuchen, thanks for the contribution! I don't have the setup to compile this project right now but the changes look good to me. I'll merge it in as soon as I make some time to verify that it's all compiling just fine.

**Comment by josefnpat** [comment]
Seems to work:

```
user@DESKTOP-4BA4H7I ~/repos
$ cd sample_images/

user@DESKTOP-4BA4H7I ~/repos/sample_images
$ ls
advdrydock.png  art.png  car.png  com.png  comm.png  drydock.png  f.png  hab.png  min.png  ref.png  s.png  sav.png  sc.png  ss.png  t.png  tank.png

user@DESKTOP-4BA4H7I ~/repos/sample_images
$ ls *.png > input.txt

user@DESKTOP-4BA4H7I ~/repos/sample_images
$ cd ..

user@DESKTOP-4BA4H7I ~/repos
$ git clone https://github.com/kerskuchen/texpack
Cloning into 'texpack'...
remote: Enumerating objects: 422, done.
remote: Total 422 (delta 0), reused 0 (delta 0), pack-reused 422
Receiving objects: 100% (422/422), 215.87 KiB | 1.93 MiB/s, done.
Resolving deltas: 100% (236/236), done.

user@DESKTOP-4BA4H7I ~/repos
$ cd texpack/

user@DESKTOP-4BA4H7I ~/repos/texpack
$ make
g++ src/main.cpp src/packer.cpp src/bleeding.cpp src/png/png.cpp src/rbp/MaxRects.cpp  -g -O2 -Wall -std=c++11   -lpng -lz -o bin/texpack
In file included from src/main.cpp:3:0:
src/getopt.h:59:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4996);

user@DESKTOP-4BA4H7I ~/repos/texpack
$ cd ../sample_images/

user@DESKTOP-4BA4H7I ~/repos/sample_images
$ ../texpack/bin/texpack.exe input.txt --output sample.png
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

sample.png.json:
```json
{"width":192,"height":416,"sprites":{"comm.png":{"x":0,"y":0,"width":128,"height":128},"advdrydock.png":{"x":0,"y":128,"width":96,"height":96},"drydock.png":{"x":96,"y":128,"width":96,"height":96},"art.png":{"x":128,"y":0,"width":64,"height":64},"car.png":{"x":128,"y":64,"width":64,"height":64},"com.png":{"x":0,"y":224,"width":64,"height":64},"hab.png":{"x":64,"y":224,"width":64,"height":64},"min.png":{"x":128,"y":224,"width":64,"height":64},"ref.png":{"x":0,"y":288,"width":64,"height":64},"s.png":{"x":64,"y":288,"width":64,"height":64},"sav.png":{"x":128,"y":288,"width":64,"height":64},"t.png":{"x":0,"y":352,"width":64,"height":64},"tank.png":{"x":64,"y":352,"width":64,"height":64},"f.png":{"x":128,"y":352,"width":32,"height":32},"sc.png":{"x":160,"y":352,"width":32,"height":32},"ss.png":{"x":128,"y":384,"width":32,"height":32}}}
```

sample png

**Comment by josefnpat** [comment]
This was built with cygwin

**Comment by urraka** [comment]
Hey @josefnpat, thanks for testing it! Just yesterday I was trying it out but the thing was crashing on me. Some issue with libpng on msys2, from what I saw. Found the same problem on master branch so whatever it was is unrelated to this change. Seems to work just fine for you so I'll ignore all of that for now and merge it. Thanks for jumping in!

**Comment by josefnpat** [comment]
Much love for you and my favorite texture packer <3

**Pull request merged**
